version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directories:
      - /
      - /ai-personas
      - /computer-languages
      - /data-languages
      - /generate-ip
      - /generate-pw
      - /geolocate
      - /latin-locales
      - /markup-languages
      - /minify.js/gulp
      - /minify.js/node.js
      - /non-latin-locales
      - /programming-languages
      - /project-markers
      - /prose-languages
      - /scss-to-css
    schedule:
      interval: daily
    cooldown:
      semver-minor-days: 7
    groups:
      prod-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
    versioning-strategy: increase

  - package-ecosystem: pip
    directories:
      - /generate-ip
      - /generate-pw
      - /geolocate
      - /minify.js
      - /scss-to-css
    schedule:
      interval: daily
    cooldown:
      semver-minor-days: 7
    groups:
      dev-dependencies:
        dependency-type: development
    versioning-strategy: increase
