name: Auto-update npm downloads + jsDelivr hits shields in root README

on:
  schedule:
    - cron: "5 0 * * *" # every day 12:05a

jobs:
  update-downloads-shield:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout adamlui/js-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/js-utils
          path: adamlui/js-utils
      
      - name: Fetch/sum download counts
        id: get-downloads
        run: |
          LC_NUMERIC=en_US # to insert commas
          npm_packages=("@adamlui/geolocate" "@adamlui/minify.js" "@adamlui/scss-to-css" "generate-ip" "generate-pw")
          jsd_packages=("@adamlui/geolocate" "generate-ip" "generate-pw")

          expand_num() { # expand nums abbreviated w/ 'k' or 'm' suffix to integers
            local num=$(echo "$1" | tr '[:upper:]' '[:lower:]') # convert to lowercase
            if [[ $num =~ k$ ]] ; then
              num="${num%k}" # remove 'k' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000 }") # multiply by 1000
            elif [[ $num =~ m$ ]] ; then
              num="${num%m}" # remove 'm' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000000 }") # multiply by 1000000
            fi ; echo "$num"
          }

          format_total() {
            local num=$1 ; first_digit="${num:0:1}" second_digit="${num:1:1}"
            second_digit=$(( second_digit < 5 ? 0 : 5 )) # round 2nd digit down
            if (( num >= 1000000000 )) ; then # 1B+ w/ one decimal place
              formatted_num="$(( num / 1000000000 ))"
              remainder=$(( (num % 1000000000) / 100000000 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="B+"
            elif (( num >= 10000000 )) ; then # abbr 10,000,000+ to 999,000,000+
              formatted_num=$(printf "%'.f+" $((( num / 1000000 ) * 1000000 )))
            elif (( num >= 1000000 )) ; then # abbr 1,000,000+ to 9,500,000+
              formatted_num="${first_digit},${second_digit}00,000+"
            elif (( num >= 100000 )) ; then # abbr 100,000+ to 950,000+
              formatted_num="${first_digit}${second_digit}0,000+"
            elif (( num >= 10000 )) ; then # abbr 10,000+ to 90,000+
              formatted_num="${first_digit}0,000+"
            elif (( num >= 1000 )) ; then # abbr 1K to 9.9K
              formatted_num="$(( num / 1000 ))"
              remainder=$(( (num % 1000) / 100 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="K"
            else formatted_num="$num" ; fi # preserve <1K as is
            echo "$formatted_num"
          }

          # Fetch/sum download counts
          for pkg in "${npm_packages[@]}" ; do
            pkg_downloads=$(curl -s "https://img.shields.io/npm/dm/$pkg.svg" |
              sed -n 's/.*<title>downloads: \([0-9,.km]\+\).*<\/title>.*/\1/Ip')
            pkg_downloads=$(expand_num "$pkg_downloads")
            echo "$pkg downloads: $pkg_downloads"
            total_downloads=$((total_downloads + pkg_downloads))
          done ; echo -e "\nTotal npm downloads: $total_downloads\n"

          # Fetch/sum jsDelivr hits
          for pkg in "${jsd_packages[@]}" ; do
            pkg_hits=$(curl -s "https://img.shields.io/jsdelivr/npm/hm/$pkg.svg" |
              sed -n -E 's|.*<title>jsdelivr: ([0-9,.km]+).*</title>.*|\1|Ip')
            pkg_hits=$(expand_num "$pkg_hits")
            echo "$pkg jsDelivr hits: $pkg_hits"
            total_hits=$((total_hits + pkg_hits))
          done ; echo -e "\nTotal jsDelivr hits: $total_hits\n"

          # Format totals
          formatted_total_downloads=$(format_total "$total_downloads")
          echo "Formatted total monthly npm downloads: $formatted_total_downloads"
          formatted_total_hits=$(format_total "$total_hits")
          echo "Formatted total monthly jsDelivr hits: $formatted_total_hits"

          # Store for update step next
          echo "total_downloads=$formatted_total_downloads" >> $GITHUB_OUTPUT
          echo "total_hits=$formatted_total_hits" >> $GITHUB_OUTPUT
      
      - name: Update README shields
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils
          total_downloads=$(echo ${{ steps.get-downloads.outputs.total_downloads }})
          total_hits=$(echo ${{ steps.get-downloads.outputs.total_hits }})
          if [ "$total_downloads" != "0" ]; then
            sed -i -E "s|(badge/Downloads-)[0-9.,km+]+|\1$total_downloads|Ig" docs/README.md ; fi
          if [ "$total_hits" != "0" ]; then
            sed -i -E "s|(badge/jsDelivr_Hits-)[0-9.,km+]+|\1$total_hits|Ig" docs/README.md ; fi

      - name: Push to adamlui/js-utils
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_author: kudo-sync-bot <auto-sync@kudoai.com>
          commit_message: Updated downloads/hits shield counters
          file_pattern: docs/README.md
          repository: adamlui/js-utils
