name: Publish data-languages to npm on new tag

on:
  push:
    tags: [data-languages*]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: |
          cd data-languages
          npm ci && npm run build && npm publish --provenance
