name: Publish generate-ip to npm on new tag

on:
  push:
    tags: [generate-ip*]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: |
          cd generate-ip
          npm ci && npm run build && npm publish --provenance
