name: Publish to NPM on new tag

on:
  release:
    types:
      - published

jobs:
  publish:
    if: ${{
           !contains(github.event.release.tag_name, 'ai-personas')
        && !contains(github.event.release.tag_name, 'minify')
        && !contains(github.event.release.tag_name, 'scss-to-css')
      }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - run: |
          TAG="${{ github.event.ref }}"
          PROJECT="${TAG#refs/tags/}"   # Remove 'refs/tags/' from the tag name
          echo "PROJECT=$PROJECT" >> $GITHUB_ENV
      - run: |
          cd ${{ env.PROJECT }} && npm ci && npm run build && npm publish --provenance
