name: Sync README.md between minify.js/<gulp|node.js>/ & minify.js/<gulp|node.js>/docs/, then minify.js/ to adamlui/minify.js

on:
  push:
    branches: [main]
    paths: [minify.js/**]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'adamlui/js-utils') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/js-utils
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          path: adamlui/js-utils
          fetch-depth: 2

      - name: Checkout adamlui/minify.js
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/minify.js
          path: adamlui/minify.js

      - name: Sync README.md between minify.js/gulp/ & minify.js/gulp/docs
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils

          # Init paths/content/mod timestamps
          root_readme="./minify.js/gulp/README.md"
          root_readme_content=$(git show HEAD:"$root_readme")
          root_readme_modified=$(git log -1 --format="%ct" -- "$root_readme")
          docs_readme="./minify.js/gulp/docs/README.md"
          docs_readme_content=$(git show HEAD:"$docs_readme")
          docs_readme_modified=$(git log -1 --format="%ct" -- "$docs_readme")

          # Perform syncs of diff READMEs
          if [[ "$root_readme_content" != "$docs_readme_content" ]] ; then
            echo "readme_updated=true" >> $GITHUB_ENV
            if (( $root_readme_modified > $docs_readme_modified )) ; then
              cp -f "$root_readme" "$docs_readme"
              echo "Copied $root_readme to $docs_readme"
            elif (( $docs_readme_modified > $root_readme_modified )) ; then
              cp -f "$docs_readme" "$root_readme"
              echo "Copied $docs_readme to $root_readme"
            fi
          fi

      - name: Sync README.md between minify.js/node.js/ & minify.js/node.js/docs
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils

          # Init paths/content/mod timestamps
          root_readme="./minify.js/node.js/README.md"
          root_readme_content=$(git show HEAD:"$root_readme")
          root_readme_modified=$(git log -1 --format="%ct" -- "$root_readme")
          docs_readme="./minify.js/node.js/docs/README.md"
          docs_readme_content=$(git show HEAD:"$docs_readme")
          docs_readme_modified=$(git log -1 --format="%ct" -- "$docs_readme")

          # Perform syncs of diff READMEs
          if [[ "$root_readme_content" != "$docs_readme_content" ]] ; then
            echo "readme_updated=true" >> $GITHUB_ENV
            if (( $root_readme_modified > $docs_readme_modified )) ; then
              cp -f "$root_readme" "$docs_readme"
              echo "Copied $root_readme to $docs_readme"
            elif (( $docs_readme_modified > $root_readme_modified )) ; then
              cp -f "$docs_readme" "$root_readme"
              echo "Copied $docs_readme to $root_readme"
            fi
          fi

      - name: Sync minify.js/ to adamlui/minify.js/
        run: |
          rsync -avhr --delete --filter='P /.*' \
            ${{ github.workspace }}/adamlui/js-utils/minify.js/ \
            ${{ github.workspace }}/adamlui/minify.js/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to adamlui/js-utils
        if: env.readme_updated
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils
          git pull && git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/js-utils/tree/main/minify.js]" || true
          git push

      - name: Push changes to adamlui/minify.js
        run: |
          cd ${{ github.workspace }}/adamlui/minify.js
          git pull && git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from https://github.com/adamlui/js-utils/tree/main/minify.js]" || true
          git push
