name: Update npm downloads + jsDelivr requests shields in root README

on:
  schedule:
    - cron: "5 0 * * *" # every day 12:05a

jobs:
  update-stats-shields:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout adamlui/js-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/js-utils
          path: adamlui/js-utils
      
      - name: Fetch/sum npm download + JSD request counts
        id: get-stats
        run: |
          LC_NUMERIC=en_US # to insert commas

          npm_pkgs=("@adamlui/geolocate" "@adamlui/minify.js" "@adamlui/scss-to-css"
                    "generate-ip" "generate-pw" "gulp-minify.js")
          jsd_npm_pkgs=("@adamlui/geolocate" "generate-ip" "generate-pw")
          jsd_gh_repos=("adamlui/js-utils" "adamlui/minify.js" "adamlui/scss-to-css")

          expand_num() { # expand nums abbreviated w/ 'k' or 'm' suffix to integers
            local num=$(echo "$1" | tr '[:upper:]' '[:lower:]') # convert to lowercase
            if [[ $num =~ k$ ]] ; then
              num="${num%k}" # remove 'k' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000 }") # multiply by 1000
            elif [[ $num =~ m$ ]] ; then
              num="${num%m}" # remove 'm' suffix
              num=$(awk "BEGIN { printf \"%.0f\", $num * 1000000 }") # multiply by 1000000
            fi ; echo "$num"
          }

          format_total() {
            local num=$1 ; first_digit="${num:0:1}" second_digit="${num:1:1}"
            second_digit_rounded=$(( second_digit < 5 ? 0 : 5 ))
            if (( num >= 1000000000 )) ; then # 1B+ w/ one decimal place
              formatted_num="$(( num / 1000000000 ))"
              remainder=$(( (num % 1000000000) / 100000000 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="B+"
            elif (( num >= 10000000 )) ; then # abbr 10,000,000+ to 999,000,000+
              formatted_num=$(printf "%'.f+" $((( num / 1000000 ) * 1000000 )))
            elif (( num >= 1000000 )) ; then # abbr 1,000,000+ to 9,500,000+
              formatted_num="${first_digit},${second_digit}00,000+"
            elif (( num >= 100000 )) ; then # abbr 100,000+ to 950,000+
              formatted_num="${first_digit}${second_digit_rounded}0,000+"
            elif (( num >= 10000 )) ; then # abbr 10,000+ to 90,000+
              formatted_num="${first_digit}0,000+"
            elif (( num >= 1000 )) ; then # abbr 1K to 9.9K
              formatted_num="$(( num / 1000 ))"
              remainder=$(( (num % 1000) / 100 ))
              if (( remainder != 0 )) ; then formatted_num+=".$remainder" ; fi
              formatted_num+="K"
            else formatted_num="$num" ; fi # preserve <1K as is
            echo "$formatted_num"
          }

          # Fetch/sum npm download counts
          for pkg in "${npm_pkgs[@]}" ; do
            pkg_downloads=$(curl -s "https://img.shields.io/npm/dm/$pkg.svg" |
              sed -n 's/.*<title>downloads: \([0-9,.km]\+\).*<\/title>.*/\1/Ip')
            pkg_downloads=$(expand_num "$pkg_downloads")
            echo "$pkg npm downloads: $pkg_downloads"
            total_downloads=$((total_downloads + pkg_downloads))
          done ; echo -e "\nTotal monthly npm downloads: $total_downloads\n"

          # Fetch/sum jsDelivr request counts for npm pkgs
          for pkg in "${jsd_npm_pkgs[@]}" ; do
            pkg_requests=$(curl -s "https://img.shields.io/jsdelivr/npm/hm/$pkg.svg" |
              sed -n -E 's|.*<title>jsdelivr: ([0-9,.km]+).*</title>.*|\1|Ip')
            pkg_requests=$(expand_num "$pkg_requests")
            echo "$pkg jsDelivr (npm) hits: $pkg_requests"
            total_pkg_requests=$((total_pkg_requests + pkg_requests))
          done ; echo -e "\nTotal monthly jsDelivr (npm) requests: $total_pkg_requests\n"

          # Fetch/sum jsDelivr request counts for GH repos
          for repo in "${jsd_gh_repos[@]}" ; do
            repo_requests=$(curl -s "https://img.shields.io/jsdelivr/gh/hm/$repo.svg" |
              sed -n -E 's|.*<title>jsdelivr: ([0-9,.km]+).*</title>.*|\1|Ip')
            repo_requests=$(expand_num "$repo_requests")
            echo "$repo jsDelivr (GH) hits: $repo_requests"
            total_repo_requests=$((total_repo_requests + repo_requests))
          done ; echo -e "\nTotal monthly jsDelivr (GH) requests: $total_repo_requests\n"

          # Format totals
          formatted_total_downloads=$(format_total "$total_downloads")
          echo "Formatted total monthly npm downloads: $formatted_total_downloads"
          formatted_total_requests=$(format_total $((total_pkg_requests + total_repo_requests)))
          echo "Formatted total monthly jsDelivr requests: $formatted_total_requests"

          # Store for update step next
          echo "total_downloads=$formatted_total_downloads" >> $GITHUB_OUTPUT
          echo "total_requests=$formatted_total_requests" >> $GITHUB_OUTPUT
      
      - name: Update README shields
        run: |
          cd ${{ github.workspace }}/adamlui/js-utils
          total_downloads="${{ steps.get-stats.outputs.total_downloads }}"
          total_requests="${{ steps.get-stats.outputs.total_requests }}"
          if [ "$total_downloads" != "0" ]; then
            sed -i -E "s|(badge/Downloads-)[0-9.,km+]+|\1$total_downloads|Ig" docs/README.md ; fi
          if [ "$total_requests" != "0" ]; then
            sed -i -E "s|(badge/jsDelivr_[^-]+-)[0-9.,km+]+|\1$total_requests|Ig" docs/README.md ; fi

      - name: Push to adamlui/js-utils
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_author: kudo-sync-bot <auto-sync@kudoai.com>
          commit_message: Updated downloads/hits shield counters
          file_pattern: docs/README.md
          repository: adamlui/js-utils
